name: Oasismail
description: 'Fast, efficient mail client for Mac, Windows, and Linux.'
website: 'http://email.webshule.com/'
category: Productivity
repository: 'https://github.com/Oasis256/Mailspring'
keywords:
    - email
    - mail
    - messaging
    - imap
    - gmail
license: GPL-3.0
screenshots:
  -
    imageUrl: 'https://getmailspring.com/static/img/hero_graphic_mac@2x.png'
    caption: 'Mailspring on Mac'
    imageLink: 'http://getmailspring.com/'
